/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e3e3e0",
        "on-primary-fixed-variant": "#2d4d3c",
        "on-tertiary-container": "#d38e02",
        "on-secondary-fixed": "#002112",
        "on-primary-container": "#82a48f",
        "inverse-on-surface": "#f1f1ee",
        "secondary-fixed-dim": "#a2d1b4",
        primary: "#032416",
        "on-error-container": "#93000a",
        tertiary: "#2d1b00",
        "on-primary-fixed": "#002113",
        "surface-container": "#eeeeeb",
        "inverse-surface": "#2f312f",
        "error-container": "#ffdad6",
        "surface-dim": "#dadad7",
        "surface-container-highest": "#e3e3e0",
        "on-surface-variant": "#424843",
        "primary-fixed": "#c7ebd4",
        secondary: "#3c674f",
        surface: "#faf9f6",
        "primary-fixed-dim": "#abcfb8",
        background: "#faf9f6",
        "secondary-container": "#beeecf",
        "primary-container": "#1a3a2a",
        "secondary-fixed": "#beeecf",
        "on-tertiary-fixed-variant": "#624000",
        error: "#ba1a1a",
        "surface-container-low": "#f4f4f0",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-background": "#1a1c1a",
        "tertiary-fixed-dim": "#ffb94c",
        "outline-variant": "#c1c8c2",
        "on-primary": "#ffffff",
        "tertiary-container": "#492e00",
        "inverse-primary": "#abcfb8",
        "on-surface": "#1a1c1a",
        "surface-tint": "#456553",
        "on-tertiary-fixed": "#291800",
        "surface-bright": "#faf9f6",
        "surface-container-high": "#e8e8e5",
        "on-error": "#ffffff",
        "on-secondary-container": "#426d55",
        outline: "#727973",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffddb2",
        "on-secondary-fixed-variant": "#244f39",
        // brand literals used directly in the markup
        cream: "#FDF6E3",
        sage: "#E4EEE8",
        gold: "#E8A020",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        gutter: "16px",
        xl: "32px",
        xs: "4px",
        md: "16px",
        unit: "4px",
        xxl: "48px",
        sm: "8px",
        "container-padding": "20px",
      },
      fontFamily: {
        "headline-lg": ["Syne", "sans-serif"],
        display: ["Syne", "sans-serif"],
        "label-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-sm": ["Syne", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-lg-mobile": ["Syne", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "headline-md": ["Syne", "sans-serif"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
